<div class="news-item">
    <a href="<?php echo $this->url(array('controller'=>'news'));?>">
        News
    </a>
    <div class="raq">&raquo;</div>
</div>
    <div class="news-item">
    <a href="<?php echo $this->url(array('controller'=>'catalog'));?>">
        Catalog
    </a>
    <div class="raq">&raquo;</div>
</div>
<!--<div class="news-item">
    <a href="<?php /*echo $this->url(array('controller'=>'arrivals'));*/?>">
        New arrivals
    </a>
    <div class="raq">&raquo;</div>
</div>
<div class="news-item">
    <a href="<?php /*echo $this->url(array('controller'=>'download'));*/?>">
        Download prices
    </a>
    <div class="raq">&raquo;</div>
</div>-->