<div class="news-item">
    <a href="<?php echo $this->url(array('controller'=>'news'));?>">
        Новости
    </a>
    <div class="raq">&raquo;</div>
</div>
    <div class="news-item">
    <a href="<?php echo $this->url(array('controller'=>'catalog'));?>">
        Каталог
    </a>
    <div class="raq">&raquo;</div>
</div>
<div class="news-item">
    <a href="<?php echo $this->url(array('controller'=>'search'));?>">
        Поиск товара
    </a>
    <div class="raq">&raquo;</div>
</div>
<!-- <div class="news-item">
    <a href="<?php /*echo $this->url(array('controller'=>'download'));*/?>">
        Download prices
    </a>
    <div class="raq">&raquo;</div>
</div>-->